// V8 My roles + Vendor application → HOWDI Admin (request info, reject, approve) → vendor workspace (products, publish → Shop).
const K = require('../k5a-pg/lib.cjs');
const { pool, check, finish, api } = K;
const LABEL = `v8 09 vendor (${process.env.V8_EXPECT_SANDBOX === '1' ? 'sandbox' : 'no-sandbox'})`;
const ADMIN = { 'x-howdi-admin-token': process.env.HOWDI_ADMIN_TOKEN || '' };
const PNG = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==';
const FORBIDDEN = /"(id|user_id|[a-z_]*_user_id|userId|howdi_id|master_id|email|phone|uuid|id_file|vendor_profile_id)"\s*:/;
(async () => {
  const started = await K.start(); check('server starts', started, K.serverLog().slice(-600)); if (!started) return finish(LABEL);
  const V = await K.member('Vani Vendor', { username: 'vani_weaves' }); const O = await K.member('Other', { username: 'other_o' });
  const notes = async (m) => ((await api('GET', '/api/v8/notifications', { token: m.token })).json.items || []);
  const role = async (m, c) => ((await api('GET', '/api/v8/me/roles', { token: m.token })).json.items || []).find((x) => x.code === c);
  const r0 = await api('GET', '/api/v8/me/roles', { token: V.token });
  check('My roles: customer permanent + others, no staff roles', r0.json.items[0].code === 'customer' && r0.json.items[0].status === 'active' && !r0.text.includes('"admin"') && (await role(V, 'vendor')).status === 'none', r0.text.slice(0, 300));
  check('workspace refused before approval', (await api('GET', '/api/v8/vendor/store', { token: V.token })).json.code === 'NOT_A_VENDOR');
  check('full PAN refused', (await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { pan: 'ABCDE1234F' } })).json.code === 'FULL_NUMBER_REFUSED');
  check('bad IFSC refused', (await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { ifsc: 'XX' } })).status === 400);
  const p = await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { business_name: 'Vani Handlooms', business_type: 'individual', category: 'Handloom & Textiles', city: 'Khammam', pincode: '507001', pickup: '2-14 Weavers Colony', pan_last4: '1234', bank_last4: '9876', ifsc: 'SBIN0001234', description: 'Ikat and cotton sarees' } });
  check('draft saved; payload has no ids', p.json.application?.status === 'draft' && p.json.application.missing.join() === 'ID proof photo,declaration' && !FORBIDDEN.test(p.text), p.text.slice(0, 300));
  await api('POST', '/api/v8/vendor/application/document', { token: V.token, body: { imageData: PNG } });
  await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { declaration: true } });
  const s = await api('POST', '/api/v8/vendor/application/submit', { token: V.token }); const A1 = s.json.application?.public_key;
  check('submitted; role pending', s.json.application?.status === 'submitted' && (await role(V, 'vendor')).status === 'pending', s.text.slice(0, 200));
  check('admin API refuses member', (await api('GET', '/api/admin/v8/vendors/applications', { token: V.token })).status === 401);
  const q = await api('GET', '/api/admin/v8/vendors/applications', { headers: ADMIN });
  check('admin queue lists it', (q.json.items || []).some((x) => x.public_key === A1), q.text.slice(0, 200));
  check('admin detail + private document', (await api('GET', `/api/admin/v8/vendors/applications/${A1}`, { headers: ADMIN })).json.application?.pan_last4 === '1234' && (await api('GET', `/api/admin/v8/vendors/applications/${A1}/document`, { headers: ADMIN })).status === 200);
  check('reason required', (await api('POST', `/api/admin/v8/vendors/applications/${A1}/decide`, { headers: ADMIN, body: { decision: 'reject' } })).json.code === 'REASON_REQUIRED');
  await api('POST', `/api/admin/v8/vendors/applications/${A1}/decide`, { headers: ADMIN, body: { decision: 'request_info', reason: 'Bank details look incorrect — please check the IFSC.' } });
  check('applicant: action needed + reason + notified', (await role(V, 'vendor')).status === 'action_needed' && (await api('GET', '/api/v8/vendor/application', { token: V.token })).json.application.note.includes('IFSC') && (await notes(V)).some((n) => /more information/.test(n.title)));
  await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { ifsc: 'SBIN0004321' } });
  check('resubmitted', (await api('POST', '/api/v8/vendor/application/submit', { token: V.token })).json.application?.status === 'submitted');
  await api('POST', `/api/admin/v8/vendors/applications/${A1}/decide`, { headers: ADMIN, body: { decision: 'reject', reason: 'Products aren’t allowed on HOWDI Shop.' } });
  check('rejected: role rejected with reason', (await role(V, 'vendor')).status === 'rejected' && /allowed/.test((await role(V, 'vendor')).reason || ''));
  const re = await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { description: 'Handwoven cotton sarees' } });
  check('reapply = new draft with answers (ID proof must be re-added)', re.json.application?.status === 'draft' && re.json.application.public_key !== A1 && re.json.application.missing.includes('ID proof photo'), re.text.slice(0, 200));
  await api('POST', '/api/v8/vendor/application/document', { token: V.token, body: { imageData: PNG } }); await api('PUT', '/api/v8/vendor/application', { token: V.token, body: { declaration: true } });
  const A2 = (await api('POST', '/api/v8/vendor/application/submit', { token: V.token })).json.application.public_key;
  check('approve needs 3 checks', (await api('POST', `/api/admin/v8/vendors/applications/${A2}/decide`, { headers: ADMIN, body: { decision: 'approve', checks: { identity: true } } })).json.code === 'CHECKS_REQUIRED');
  const ap = await api('POST', `/api/admin/v8/vendors/applications/${A2}/decide`, { headers: ADMIN, body: { decision: 'approve', checks: { identity: true, tax: true, bank: true } } });
  check('approved', ap.json.application?.status === 'approved' && ap.json.store?.name === 'Vani Handlooms', ap.text.slice(0, 200));
  const vr = await role(V, 'vendor'); check('My roles: vendor active with workspace route', vr.status === 'active' && vr.open_route === '/me/vendor/store');
  check('vendor notified', (await notes(V)).some((n) => /is approved/.test(n.title)));
  const st = await api('GET', '/api/v8/vendor/store', { token: V.token }); check('workspace opens (store online, verified)', st.json.store?.status === 'online' && st.json.store.name === 'Vani Handlooms', st.text.slice(0, 200));
  check('product validation', (await api('POST', '/api/v8/vendor/products', { token: V.token, body: { name: 'Saree', price: 900, mrp: 800 } })).status === 400);
  const pr = await api('POST', '/api/v8/vendor/products', { token: V.token, body: { name: 'Ikat cotton saree', price: 1800, mrp: 2200, stock: 4, category: 'Handloom & Textiles' } });
  const PRD = pr.json.product?.public_key; check('product created as draft', pr.status === 201 && /^PRD-/.test(PRD || '') && pr.json.product.status === 'draft', pr.text.slice(0, 200));
  check('publish needs a photo', (await api('POST', `/api/v8/vendor/products/${PRD}/publish`, { token: V.token })).json.code === 'NEEDS_PHOTO');
  const pa = await api('PATCH', `/api/v8/vendor/products/${PRD}`, { token: V.token, body: { imageData: PNG, stock: 5 } });
  check('photo + stock updated', pa.json.product?.images?.length === 1 && pa.json.product.stock === 5, pa.text.slice(0, 300));
  const pb = await api('POST', `/api/v8/vendor/products/${PRD}/publish`, { token: V.token }); check('published', pb.json.product?.status === 'published', pb.text.slice(0, 300));
  check('buyers find it in Shop search', ((await api('GET', '/api/search?q=ikat&types=product', { token: O.token })).json.results || []).some((x) => x.route === `/shop/products/${PRD}`));
  check('another member cannot edit it', (await api('PATCH', `/api/v8/vendor/products/${PRD}`, { token: O.token, body: { price: 1 } })).status === 403);
  check('unpublish hides it', (await api('POST', `/api/v8/vendor/products/${PRD}/unpublish`, { token: V.token })).json.product?.status === 'draft' && !((await api('GET', '/api/search?q=ikat&types=product', { token: O.token })).json.results || []).length);
  check('audit has the 3 vendor decisions', Number((await pool.query(`SELECT COUNT(*) n FROM howdi_admin_security_audit WHERE action='V8_VENDOR_APP_DECISION'`)).rows[0].n) === 3);
  await finish(LABEL);
})().catch(async (e) => { check('suite ran to the end', false, e && e.stack); await finish(LABEL); });
