import { useCallback, useEffect, useState } from 'react';
import { RidePanel, RideField, rupees, rideWhen } from '../works/Rides';
const BASE = '/api/admin/v8/rides';
const errorText = (r, fallback) => r?.json?.message || fallback;

export default function RidesAdmin({ call }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [stale, setStale] = useState(false);
  const load = useCallback(async () => { setError(''); try { const r = await call('GET', BASE); if (r.ok) { setData(r.json); setStale(false); } else { setError(r.status === 401 ? 'Your staff session is no longer authorized. Sign in again.' : errorText(r, 'Could not load the Ride operations queue.')); setStale(true); } } catch { setError('Network interruption. Reconnect and retry before taking any action.'); setStale(true); } }, [call]);
  useEffect(() => { load(); }, [load]);
  const act = async (path, body) => { if (busy || stale) return false; setBusy(true); setError(''); try { const r = await call('POST', BASE + path, body); if (!r.ok) { setError(r.status === 401 ? 'Your staff session is no longer authorized. Sign in again.' : errorText(r, 'The server rejected this action. Refresh the queue.')); setStale(true); return false; } await load(); return true; } catch { setError('No confirmation received. Refresh the queue before retrying.'); setStale(true); return false; } finally { setBusy(false); } };
  if (!data && !error) return <div className="ride-admin"><p className="v8a-muted" role="status">Loading Ride operations…</p></div>;
  return <div className="ride-admin"><div className="ride-banner">STAFF ONLY · LOCAL PREVIEW / TEST · PRODUCTION GATE CLOSED</div><header className="ride-admin-head"><div><span className="ride-eyebrow">HOWDI Admin / Move</span><h1>Ride operations</h1><p>Use public Ride codes and @handles. Dispatch, eligibility, payment and privacy checks stay server-authoritative.</p></div><button type="button" onClick={load} disabled={busy}>Refresh queue</button></header>
    {error && <p role="alert" className="ride-alert">{error} <button type="button" onClick={load}>Retry</button></p>}{stale && data && <p role="status" className="ride-alert">Queue data may have changed. Refresh before acting.</p>}
    {data && <fieldset disabled={busy || stale} className="ride-body" aria-busy={busy}><p className="ride-admin-rbac"><b>Authorization:</b> {data.rbac?.mode === 'staff_session_only' ? 'The server currently verifies a staff session only.' : 'Server authorization status unavailable.'} {data.rbac?.gap || 'Capability-specific roles are not configured.'} Move City Ops, Driver Onboarding, Safety, Support, Finance, Fraud/Compliance and Audit roles remain a backend dependency; this UI does not pretend they are enforced.</p>
      <RidePanel id="ADM-RIDE-001" title="Driver verification"><p>Review the vehicle-class application and private evidence before approving. Approved drivers can be restricted from Move Preview with a recorded reason.</p>{!data.applications?.length ? <Empty text="No driver applications in this queue." /> : data.applications.map(a => <DriverApplication key={a.code} application={a} checks={data.checks || []} act={act} call={call} />)}</RidePanel>
      <RidePanel id="ADM-RIDE-002" title="Dispatch and operations"><p>{data.zone} · Preview/Test only. Manual dispatch rechecks the driver account, restriction, block relationship, class, zone, accessibility, Ride state and overlap on the server.</p><div className="ride-admin-grid">{['Auto', 'Cab'].map(cls => <ZoneGate key={cls} cls={cls} zone={data.zones?.find(z => z.vehicle_class === cls)} checks={data.pilot_checks || []} act={act} />)}</div>{!data.rides?.length ? <Empty text="No active or historical Rides." /> : data.rides.map(ride => <RideOperation key={ride.code} ride={ride} act={act} />)}<h3>Timed offers</h3>{data.offers?.length ? data.offers.map(o => <p key={o.code}><b>{o.ride_code}</b> → @{o.driver} · {o.state} · expires {rideWhen(o.expires_at)}</p>) : <Empty text="No timed offers." />}</RidePanel>
      <RidePanel id="ADM-RIDE-003" title="Incident and support"><p>Cases use public case and Ride codes. Resolution is recorded with a reason and notifies affected participants. Escalation ownership/SLA is not yet a server capability.</p>{!data.cases?.length ? <Empty text="No support or incident cases." /> : data.cases.map(c => <SupportCase key={c.code} caseItem={c} act={act} />)}</RidePanel>
      <RidePanel id="ADM-RIDE-005" title="Preview payment and reconciliation"><p>Only Preview/Test payment and settlement states appear. No production finance action or payout claim is available.</p>{!data.rides?.filter(r => r.state === 'completed').length ? <Empty text="No completed Rides awaiting review." /> : data.rides.filter(r => r.state === 'completed').map(r => <Settlement key={r.code} ride={r} act={act} />)}</RidePanel>
      <RidePanel id="ADM-RIDE-006" title="Recent audit trail"><p>Actor, action, timestamp, public reference and safe before/after details are supplied by the server. Secrets and private evidence are not included.</p>{data.audit?.length ? <div className="ride-audit">{data.audit.map((a, index) => <article key={`${a.ref}-${a.created_at}-${index}`}><b>{a.ref}</b><span>{a.actor} · {a.action.replaceAll('_', ' ')} · {rideWhen(a.created_at)}</span><small>{auditDetail(a.detail)}</small></article>)}</div> : <Empty text="No Ride audit events yet." />}</RidePanel>
    </fieldset>}</div>;
}

function Empty({ text }) { return <p className="v8a-empty">{text}</p>; }
function auditDetail(detail = {}) { return ['from', 'to', 'reason', 'method', 'kind', 'case', 'checks'].filter(k => detail[k] !== undefined).map(k => `${k}: ${Array.isArray(detail[k]) ? detail[k].join(', ') : detail[k]}`).join(' · ') || 'Recorded by server'; }
function ConfirmAction({ label, choices, run }) { const [reason, setReason] = useState(''), [pending, setPending] = useState(''); return <div className="ride-admin-action"><b>{label}</b><RideField label="Required reason"><textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={300} /></RideField>{choices.map(choice => <button type="button" key={choice} disabled={!reason.trim()} onClick={() => setPending(choice)}>{choice}</button>)}{pending && <div className="ride-alert"><p>Confirm “{pending}”? The server will revalidate the current state and record this reason.</p><button type="button" className="ride-primary" onClick={() => { run(pending, reason); setPending(''); }}>Confirm</button><button type="button" onClick={() => setPending('')}>Keep unchanged</button></div>}</div>; }
function DriverApplication({ application: a, checks, act, call }) { const [docs, setDocs] = useState(null), [checked, setChecked] = useState({}); return <article className="ride-offer"><header className="ride-admin-row"><div><span className="ride-eyebrow">{a.code}</span><h3>@{a.handle} · {a.vehicle_class}</h3><p>{a.state.replaceAll('_', ' ')} · {a.eligible_now ? 'eligible now' : 'not eligible now'} · {a.available ? 'online' : 'offline'} · {a.zone}</p></div><span className={a.eligible_now ? 'ride-status-ok' : 'ride-status-off'}>{a.eligible_now ? 'Eligible' : 'Unavailable'}</span></header><p>Vehicle: {a.details.plate || 'not supplied'} · documents: {a.document_kinds?.length || 0}/6</p>{a.reason && <p className="ride-notice">Reason: {a.reason}</p>}<button type="button" onClick={async () => { const r = await call('GET', `${BASE}/applications/${a.code}/documents`); if (r.ok) setDocs(r.json.documents); }}>{docs ? 'Refresh private evidence' : 'Open private evidence (audited)'}</button>{docs && <div className="ride-docs">{docs.map(d => <figure key={d.kind}><figcaption>{d.kind}</figcaption><img src={d.image} alt={`${d.kind} verification evidence`} /></figure>)}</div>}{a.state === 'submitted' && <><p>Check each condition after opening the evidence. Approval is per vehicle class.</p>{checks.map(check => <label className="ride-check" key={check}><input type="checkbox" checked={!!checked[check]} onChange={e => setChecked({ ...checked, [check]: e.target.checked })} />{check.replaceAll('_', ' ')}</label>)}<ConfirmAction label="Verification decision" choices={['Request information', 'Reject', 'Approve']} run={(choice, reason) => act(`/applications/${a.code}/decide`, { reason, decision: { Approve: 'approved', Reject: 'rejected', 'Request information': 'info_requested' }[choice], checks: checked })} /></>}{a.state === 'approved' && <ConfirmAction label="Move Preview restriction" choices={['Suspend / restrict driver']} run={(_, reason) => act(`/applications/${a.code}/restrict`, { reason })} />}</article>; }
function RideOperation({ ride, act }) { const [handle, setHandle] = useState(''); return <article className="ride-offer"><header className="ride-admin-row"><div><span className="ride-eyebrow">{ride.code}</span><h3>{ride.state.replaceAll('_', ' ')}</h3></div><span>{ride.quote.vehicle_class} · {ride.quote.mode === 'instant' ? 'Ride now' : rideWhen(ride.quote.scheduled_at)}</span></header><p>@{ride.customer} → {ride.driver ? '@' + ride.driver : 'Unassigned'} · {rupees(ride.quote.fare.total)} · {ride.payment_state} · settlement {ride.payout_state}</p>{ride.state === 'requested' && <><RideField label="Available driver @handle"><input value={handle} onChange={e => setHandle(e.target.value)} placeholder="public handle only" /></RideField><ConfirmAction label="Manual dispatch" choices={['Send Ride offer']} run={(_, reason) => act(`/${ride.code}/assign`, { handle, reason })} /></>}</article>; }
function ZoneGate({ cls, zone, checks, act }) { const [confirmed, setConfirmed] = useState(zone?.preview_checks || {}); const enabled = !!zone && !zone.paused && checks.every(k => zone.preview_checks?.[k]); return <article className="ride-offer"><h3>{cls} · {enabled ? 'Preview enabled' : 'Paused or closed'}</h3><p>All gates are required to enable Preview. Women Special is not configurable here and has no dispatch fallback.</p>{checks.map(check => <label key={check} className="ride-check"><input type="checkbox" checked={!!confirmed[check]} onChange={e => setConfirmed({ ...confirmed, [check]: e.target.checked })} />{check.replaceAll('_', ' ')} reviewed</label>)}<ConfirmAction label="Zone decision" choices={['Enable Preview', 'Pause Preview']} run={(choice, reason) => act('/zone', { vehicle_class: cls, paused: choice === 'Pause Preview', reason, preview_checks: confirmed })} /></article>; }
function SupportCase({ caseItem: c, act }) { return <article className="ride-offer"><span className="ride-eyebrow">{c.code} · {c.ride_code}</span><h3>{c.kind.replaceAll('_', ' ')} · {c.state}</h3><p>{c.reason}</p>{c.state === 'open' ? <ConfirmAction label="Resolution" choices={['Resolve without fee', 'Test full refund']} run={(choice, reason) => act(`/cases/${c.code}`, { reason, refund: choice === 'Test full refund' })} /> : <p className="ride-notice">Resolution: {c.resolution}</p>}</article>; }
function Settlement({ ride, act }) { return <article className="ride-offer"><b>{ride.code}</b><p>{ride.payment_state} · settlement {ride.payout_state} · {rupees(ride.quote.fare.total)}</p><ConfirmAction label="Preview reconciliation" choices={['Hold settlement', 'Release settlement']} run={(choice, reason) => act(`/${ride.code}/payout`, { reason, state: choice === 'Hold settlement' ? 'held' : 'released' })} /></article>; }
