import { useCallback, useEffect, useState } from 'react';
import { RidePanel, RideField, rupees, rideWhen } from '../works/Rides';
const BASE = '/api/admin/v8/rides';
export default function RidesAdmin({ call }) {
  const [data, setData] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const r = await call('GET', BASE); if (r.ok) setData(r.json); else setError(r.json.message); } catch { setError('Offline. Reconnect to refresh the staff queue.'); } }, [call]);
  useEffect(() => { load(); }, [load]);
  const act = async (path, body) => { if (busy) return; setBusy(true); setError(''); try { const r = await call('POST', BASE + path, body); if (!r.ok) setError(r.json.message); else await load(); } catch { setError('Connection failed. Refresh before retrying.'); } finally { setBusy(false); } };
  return <div className="ride-admin"><div className="ride-banner">STAFF ONLY · LOCAL PREVIEW / TEST · PRODUCTION GATE CLOSED</div><h1>Rides verification & operations</h1>{error && <p role="alert" className="ride-alert">{error}</p>}<button onClick={load}>Refresh queues</button>{!data ? <p>Loading staff queue…</p> : <fieldset disabled={busy} style={{ border: 0, padding: 0, minWidth: 0 }}>
    <RidePanel id="ADM-RIDE-001" title="Per-class verification">{!data.applications.length && <p>No applications received.</p>}{data.applications.map(a => <Application key={a.code + a.state} a={a} checks={data.checks} act={act} call={call} />)}</RidePanel>
    <RidePanel id="ADM-RIDE-004" title="Document expiry"><p>Expired documents block every offer and trip start. Opening this queue also disables expired approvals and notifies the driver.</p>{data.applications.map(a => <p key={a.code}>@{a.handle} · {a.vehicle_class} · {a.eligible_now ? 'Valid now' : 'Not eligible'}<br />Licence {a.details.licence_until} · Permit {a.details.permit_until} · Insurance {a.details.insurance_until}</p>)}</RidePanel>
    <RidePanel id="ADM-RIDE-002" title="Offers, bookings & zone control"><p>{data.zone}. Zone controls affect Preview/Test only.</p>{["Auto", "Cab"].map(cls => <ZoneGate key={cls} cls={cls} zone={data.zones.find(z=>z.vehicle_class===cls)} checks={data.pilot_checks || []} act={act} />)}{data.offers?.map(o=><p key={o.code}>{o.ride_code} → @{o.driver} · {o.state} · offer deadline {rideWhen(o.expires_at)}</p>)}{data.rides.map(r => <article className="ride-offer" key={r.code}><b>{r.code} · {r.state}</b><p>{rideWhen(r.quote.scheduled_at)} · {r.quote.vehicle_class} · @{r.customer} → {r.driver ? '@' + r.driver : 'Unassigned'}</p><p>{rupees(r.quote.fare.total)} · {r.payment_state}</p>{r.state === "requested" && <Assignment ride={r} act={act} />}</article>)}</RidePanel>
    <RidePanel id="ADM-RIDE-003" title="Incidents, lost items & fee review">{!data.cases.length && <p>No support cases.</p>}{data.cases.map(c => <article key={c.code} className="ride-offer"><h3>{c.kind.replaceAll('_', ' ')} · {c.state}</h3><b>{c.code} / {c.ride_code}</b><p>{c.reason}</p>{c.state === 'open' ? <Decision label="Decision with notice and appeal path" choices={['Resolve without fee', 'Test full refund']} run={(choice, reason) => act(`/cases/${c.code}`, { reason, refund: choice === 'Test full refund' })} /> : <p>{c.resolution}</p>}</article>)}</RidePanel>
    <RidePanel id="ADM-RIDE-005" title="Passenger payout review"><p>Test records only. Release requires reconciliation and a different reviewer from the hold reviewer. Both participants receive a notice and can appeal.</p>{data.rides.filter(r => r.state === 'completed').map(r => <Decision key={r.code} label={`${r.code} · ${r.payout_state}`} choices={['Hold', 'Release']} run={(choice, reason) => act(`/${r.code}/payout`, { reason, state: choice === 'Hold' ? 'held' : 'released' })} />)}</RidePanel>
  </fieldset>}</div>;
}
function Decision({ label, choices, run }) { const [reason, setReason] = useState(''), [confirm, setConfirm] = useState(''); return <div className="ride-offer"><b>{label}</b><RideField label="Required reason"><textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={300} /></RideField>{choices.map(c => <button key={c} disabled={!reason.trim()} onClick={() => setConfirm(c)}>{c}</button>)}{confirm && <div className="ride-alert"><p>Confirm “{confirm}”? The decision, reason and notice will be recorded.</p><button onClick={() => { run(confirm, reason); setConfirm(''); }}>Confirm decision</button><button onClick={() => setConfirm('')}>Keep unchanged</button></div>}</div>; }
function Application({ a, checks, act, call }) { const [docs, setDocs] = useState(null), [checked, setChecked] = useState({}); return <article className="ride-offer"><h3>@{a.handle} · {a.vehicle_class}</h3><p>{a.state} · {a.zone} · {a.details.plate}</p><p>{a.reason}</p><button onClick={async () => { const r = await call('GET', `${BASE}/applications/${a.code}/documents`); if (r.ok) setDocs(r.json.documents); }}>Open private evidence (audited)</button>{docs && <div className="ride-docs">{docs.map(d => <figure key={d.kind}><figcaption>{d.kind}</figcaption><img src={d.image} alt={`${d.kind} verification evidence`} /></figure>)}</div>}{a.state === 'submitted' && <><p>Review each document and the exact vehicle class. There is no bulk approval.</p>{checks.map(k => <label className="ride-check" key={k}><input type="checkbox" checked={!!checked[k]} onChange={e => setChecked({ ...checked, [k]: e.target.checked })} />{k.replaceAll('_', ' ')}</label>)}<Decision label="Verification decision" choices={['Request information', 'Reject', 'Approve']} run={(choice, reason) => act(`/applications/${a.code}/decide`, { reason, decision: { Approve: 'approved', Reject: 'rejected', 'Request information': 'info_requested' }[choice], checks: checked })} /></>}</article>; }

function Assignment({ ride, act }) { const [handle, setHandle] = useState(""); return <><RideField label="Available driver @handle"><input value={handle} onChange={e => setHandle(e.target.value)} /></RideField><Decision label="Offer to driver; acceptance remains their decision" choices={["Send scheduled offer"]} run={(_, reason) => act(`/${ride.code}/assign`, { handle, reason })} /></>; }

function ZoneGate({cls,zone,checks,act}) { const [confirmed,setConfirmed]=useState(zone?.preview_checks||{});const open=zone&&!zone.paused&&checks.every(k=>zone.preview_checks?.[k]);return <div className="ride-offer"><h3>{cls} · {open?"Preview enabled":"Closed / paused"}</h3><p>Review the local test-pilot controls. This does not authorize production transport.</p>{checks.map(k=><label key={k} className="ride-check"><input type="checkbox" checked={!!confirmed[k]} onChange={e=>setConfirmed({...confirmed,[k]:e.target.checked})} />Preview {k.replaceAll("_"," ")} gate reviewed</label>)}<Decision label="Class / zone decision" choices={["Enable preview", "Pause"]} run={(choice,reason)=>act("/zone",{vehicle_class:cls,paused:choice==="Pause",reason,preview_checks:confirmed})} /></div>; }
