const fs=require('fs');const path=require('path');const http=require('http');const crypto=require('crypto');
const PORT=5000,HOST='127.0.0.1',DATA_DIR=path.join(__dirname,'data');if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const FILES={users:path.join(DATA_DIR,'users.json'),addresses:path.join(DATA_DIR,'addresses.json'),products:path.join(DATA_DIR,'products.json'),orders:path.join(DATA_DIR,'orders.json'),wishlist:path.join(DATA_DIR,'wishlist.json'),cart:path.join(DATA_DIR,'cart.json'),wallet:path.join(DATA_DIR,'wallet.json'),notifications:path.join(DATA_DIR,'notifications.json'),serviceability:path.join(DATA_DIR,'serviceability.json')};
const readJSON=(f,d=[])=>{try{return JSON.parse(fs.readFileSync(f,'utf8'));}catch{return d;}};const writeJSON=(f,d)=>fs.writeFileSync(f,JSON.stringify(d,null,2));Object.values(FILES).forEach(f=>{if(!fs.existsSync(f))writeJSON(f,[])});
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString(),normalizePhone=v=>String(v||'').replace(/\D/g,''),sendJSON=(res,status,body)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'http://localhost:5173','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization'});res.end(JSON.stringify(body));};
const parseBody=req=>new Promise((resolve,reject)=>{let raw='';req.on('data',c=>raw+=c);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)});const hashPassword=p=>crypto.createHash('sha256').update(String(p)).digest('hex');
const server=http.createServer(async(req,res)=>{if(req.method==='OPTIONS')return sendJSON(res,204,{});const url=new URL(req.url,`http://${req.headers.host||'localhost'}`),pathname=url.pathname;try{
if(req.method==='GET'&&pathname==='/api/health')return sendJSON(res,200,{status:'ok',message:'HOWDI Backend is running'});
if(req.method==='POST'&&pathname==='/api/auth/register'){const b=await parseBody(req),name=String(b.name||b.fullName||b.full_name||'').trim(),phone=normalizePhone(b.phone||b.mobile),email=String(b.email||`${phone}@howdi.local`).trim().toLowerCase(),password=String(b.password||'');if(!name||!phone||password.length<6)return sendJSON(res,400,{status:'error',message:'Name, phone and password (minimum 6 characters) are required'});const users=readJSON(FILES.users,[]);if(users.some(u=>normalizePhone(u.phone)===phone||String(u.email).toLowerCase()===email))return sendJSON(res,409,{status:'error',message:'Account already exists'});const u={id:id(),name,email,phone,password_hash:hashPassword(password),created_at:now()};users.push(u);writeJSON(FILES.users,users);return sendJSON(res,201,{status:'success',message:'Account created successfully!',user:{id:u.id,name:u.name,email:u.email,phone:u.phone}})}
if(req.method==='POST'&&pathname==='/api/auth/login'){const b=await parseBody(req),identifier=String(b.phone||b.mobile||b.email||'').trim(),users=readJSON(FILES.users,[]),u=users.find(x=>normalizePhone(x.phone)===normalizePhone(identifier)||String(x.email).toLowerCase()===identifier.toLowerCase());if(!u||u.password_hash!==hashPassword(b.password||''))return sendJSON(res,401,{status:'error',message:'Invalid phone/email or password'});return sendJSON(res,200,{status:'success',message:'Login successful',user:{id:u.id,name:u.name,email:u.email,phone:u.phone}})}
// ADMIN-CONTROLLED LOCATION SERVICEABILITY
if(req.method==='GET'&&pathname==='/api/admin/serviceability')return sendJSON(res,200,{status:'success',locations:readJSON(FILES.serviceability,[])});
if(req.method==='POST'&&pathname==='/api/admin/serviceability'){const b=await parseBody(req),pincode=String(b.pincode||'').replace(/\D/g,'').slice(0,6),city=String(b.city||'').trim(),state=String(b.state||'').trim(),serviceable=b.serviceable!==false;if(pincode.length!==6||!city||!state)return sendJSON(res,400,{status:'error',message:'Valid 6-digit pincode, city and state are required'});const a=readJSON(FILES.serviceability,[]),i=a.findIndex(x=>x.pincode===pincode&&x.city.toLowerCase()===city.toLowerCase()),record={id:i>=0?a[i].id:id(),pincode,city,state,serviceable,updatedAt:now()};if(i>=0)a[i]=record;else a.push(record);writeJSON(FILES.serviceability,a);return sendJSON(res,i>=0?200:201,{status:'success',message:i>=0?'Serviceability updated':'Serviceability location added',location:record})}
if(req.method==='POST'&&pathname==='/api/admin/serviceability/delete'){const b=await parseBody(req),a=readJSON(FILES.serviceability,[]),n=a.filter(x=>x.id!==String(b.id||''));if(n.length===a.length)return sendJSON(res,404,{status:'error',message:'Location not found'});writeJSON(FILES.serviceability,n);return sendJSON(res,200,{status:'success',message:'Serviceability location deleted'})}
if(req.method==='GET'&&pathname==='/api/serviceability/check'){const pincode=String(url.searchParams.get('pincode')||'').replace(/\D/g,'').slice(0,6),city=String(url.searchParams.get('city')||'').trim().toLowerCase();if(pincode.length!==6)return sendJSON(res,400,{status:'error',message:'Please enter a valid 6-digit pincode.'});const match=readJSON(FILES.serviceability,[]).find(x=>x.pincode===pincode&&x.city.toLowerCase()===city);return sendJSON(res,200,{status:'success',serviceable:Boolean(match&&match.serviceable),message:match&&match.serviceable?'HOWDI is available in your location.':'HOWDI is coming soon to your location 🚀',location:match||null})}
// ADDRESS BOOK
if(pathname==='/api/addresses'&&req.method==='GET'){const c=url.searchParams.get('customer_id')||'';if(!c)return sendJSON(res,400,{status:'error',message:'customer_id is required'});return sendJSON(res,200,{status:'success',addresses:readJSON(FILES.addresses,[]).filter(a=>String(a.customer_id)===c)})}
if(pathname==='/api/addresses'&&req.method==='POST'){const b=await parseBody(req),c=String(b.customer_id||'').trim(),full=String(b.full_name||b.name||'').trim(),line=String(b.address_line1||b.address||'').trim(),city=String(b.city||'').trim(),state=String(b.state||'').trim(),pin=String(b.pincode||'').replace(/\D/g,'').slice(0,6),phone=normalizePhone(b.phone||b.mobile);if(!c||!full||!line||!city||!state||pin.length!==6||!phone)return sendJSON(res,400,{status:'error',message:'Complete address details are required'});const loc=readJSON(FILES.serviceability,[]).find(x=>x.pincode===pin&&x.city.toLowerCase()===city.toLowerCase()&&x.state.toLowerCase()===state.toLowerCase()&&x.serviceable!==false);if(!loc)return sendJSON(res,400,{status:'error',message:'Please select a valid HOWDI serviceable State, City and Pincode.'});const a=readJSON(FILES.addresses,[]),def=a.filter(x=>String(x.customer_id)===c).length===0,r={id:id(),customer_id:c,label:String(b.label||'Home'),full_name:full,phone,address_line1:line,address_line2:String(b.address_line2||''),city,state,pincode:pin,address:line,is_default:Boolean(b.is_default)||def,created_at:now(),updated_at:now()};if(r.is_default)a.forEach(x=>{if(String(x.customer_id)===c)x.is_default=false});a.push(r);writeJSON(FILES.addresses,a);return sendJSON(res,201,{status:'success',address:r})}
const am=pathname.match(/^\/api\/addresses\/([^/]+)$/),dm=pathname.match(/^\/api\/addresses\/([^/]+)\/default$/);if(dm&&req.method==='POST'){const b=await parseBody(req),c=String(b.customer_id||url.searchParams.get('customer_id')||''),a=readJSON(FILES.addresses,[]),t=a.find(x=>x.id===decodeURIComponent(dm[1])&&String(x.customer_id)===c);if(!t)return sendJSON(res,404,{status:'error',message:'Address not found'});a.forEach(x=>{if(String(x.customer_id)===c)x.is_default=x.id===t.id});writeJSON(FILES.addresses,a);return sendJSON(res,200,{status:'success',address:t})}
if(am&&(req.method==='PUT'||req.method==='DELETE')){const b=req.method==='PUT'?await parseBody(req):{},c=String(b.customer_id||url.searchParams.get('customer_id')||''),a=readJSON(FILES.addresses,[]),i=a.findIndex(x=>x.id===decodeURIComponent(am[1])&&String(x.customer_id)===c);if(i<0)return sendJSON(res,404,{status:'error',message:'Address not found'});if(req.method==='DELETE'){const d=a.splice(i,1)[0];if(d.is_default){const n=a.find(x=>String(x.customer_id)===c);if(n)n.is_default=true}writeJSON(FILES.addresses,a);return sendJSON(res,200,{status:'success',message:'Address deleted'})}const old=a[i],r={...old,...b,id:old.id,customer_id:old.customer_id,full_name:String(b.full_name??old.full_name).trim(),address_line1:String(b.address_line1??b.address??old.address_line1??'').trim(),address_line2:String(b.address_line2??old.address_line2??''),city:String(b.city??old.city??'').trim(),state:String(b.state??old.state??'').trim(),pincode:String(b.pincode??old.pincode??'').replace(/\D/g,'').slice(0,6),phone:normalizePhone(b.phone??old.phone),updated_at:now()};const loc=readJSON(FILES.serviceability,[]).find(x=>x.pincode===r.pincode&&x.city.toLowerCase()===r.city.toLowerCase()&&x.state.toLowerCase()===r.state.toLowerCase()&&x.serviceable!==false);if(!loc)return sendJSON(res,400,{status:'error',message:'Please select a valid HOWDI serviceable State, City and Pincode.'});r.address=r.address_line1;if(r.is_default)a.forEach(x=>{if(String(x.customer_id)===c)x.is_default=false});a[i]=r;writeJSON(FILES.addresses,a);return sendJSON(res,200,{status:'success',address:r})}
if(req.method==='GET'&&pathname==='/api/products'){let p=readJSON(FILES.products,[]),q=String(url.searchParams.get('q')||'').toLowerCase(),cat=String(url.searchParams.get('category')||'').toLowerCase();if(q)p=p.filter(x=>String(x.name).toLowerCase().includes(q)||String(x.category).toLowerCase().includes(q));if(cat)p=p.filter(x=>String(x.category).toLowerCase()===cat);return sendJSON(res,200,{status:'success',products:p})}
if(req.method==='GET'&&pathname==='/api/orders'){const c=url.searchParams.get('customer_id')||'';return sendJSON(res,200,{status:'success',orders:readJSON(FILES.orders,[]).filter(o=>!c||String(o.customer_id)===c)})}if(req.method==='POST'&&pathname==='/api/orders'){const b=await parseBody(req),a=readJSON(FILES.orders,[]),o={id:id(),order_id:`HOWDI-${Date.now()}`,...b,status:'PLACED',created_at:now(),updated_at:now()};a.push(o);writeJSON(FILES.orders,a);return sendJSON(res,201,{status:'success',order:o})}
return sendJSON(res,404,{status:'error',message:'API endpoint not found'});
}catch(e){console.error(e);return sendJSON(res,500,{status:'error',message:e.message||'Internal server error'})}});
server.listen(PORT,HOST,()=>{console.log('HOWDI BACKEND V2');console.log(`API: http://${HOST}:${PORT}`);console.log(`Health: http://${HOST}:${PORT}/api/health`);console.log(`Orders: http://${HOST}:${PORT}/api/orders`)});
