'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const src=fs.readFileSync(path.join(__dirname,'../global-search-k5b.cjs'),'utf8');
const {createGlobalSearchK5B,SEARCH_TYPES,_internal}=require('../global-search-k5b.cjs');
const {createConnectHomeK5A,FORBIDDEN_KEY_RE}=require('../connect-home-k5a.cjs');
const cpv=(a,v)=>`CPV(${a},${v})`,ppo=(o,v)=>`PPO(${o},${v})`,ws=(s)=>s.replace(/\s+/g,' ').trim();
test('search input contract is bounded and type-scoped',()=>{assert.match(src,/q\.length<2/);assert.match(src,/q\.length>80/);assert.match(src,/Math\.max\(1,Math\.min\(20/);assert.deepEqual([...SEARCH_TYPES],['people','creators','posts','articles','vibes','groups','channels','products','workers']);assert.match(src,/!TYPES\.includes\(type\)/);assert.match(src,/INVALID_TYPE/);});
test('people DTO is an explicit public allow-list',()=>{const m=src.match(/map\(x=>\(\{(type:'person'[^}]+)\}\)\)/);assert.ok(m);for(const key of ['type','public_username','display_name','avatar_url','headline','route'])assert.match(m[1],new RegExp('\\b'+key+'\\s*:'));assert.doesNotMatch(m[1],/\bid\s*:|email|phone|address|uuid|howdi_id|master_id/i);});
test('people ordering is exact then prefix then contains',()=>{assert.match(src,/CASE WHEN LOWER\(p\.public_username\)=\$4 THEN 0 WHEN LOWER\(p\.public_username\) LIKE \$1\|\|'%'/);});
test('people exact match uses raw $4; prefix/contains stay on escaped $1; bound as [like,vid,limit,exact]',()=>{const p=src.slice(src.indexOf("if(type==='people')"),src.indexOf('[like,vid,limit,exact])'));assert.ok(p.length>100);assert.doesNotMatch(p,/LOWER\(p\.public_username\)=\$1/);assert.equal((p.match(/LOWER\(p\.public_username\)=\$4/g)||[]).length,2);
  assert.match(p,/LOWER\(p\.public_username\) LIKE \$1\|\|'%' ESCAPE/);assert.match(p,/LOWER\(COALESCE\(u\.full_name,''\)\) LIKE '%'\|\|\$1\|\|'%' ESCAPE/);assert.match(p,/k5ePrivateProfileOkSql\('p\.user_id','\$2::bigint'\)/);});

// ---- K5A parity: search visibility fragments must be byte-identical (modulo whitespace) to the K5A Home SQL
const k5a=createConnectHomeK5A({pool:{},getSessionUserFromRequest:async()=>null,sendJSON(){},connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo,env:{HOWDI_HOME_CURSOR_KEY:'k'.repeat(40)},logger:{warn(){},error(){}}})._internal.SQL;
const F=_internal.k5aFragments({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});
test('post visibility is the K5A POST_WHERE built on the injected connectPostVisibleSql',()=>{assert.ok(ws(k5a.feedCandidates).includes(ws(F.POST_WHERE)));assert.ok(F.POST_WHERE.includes("CPV(p,$1::bigint)"));});
test('vibe visibility is the K5A Discover Vibes predicate (incl. bidirectional vibe_creator_blocks)',()=>{assert.ok(ws(k5a.vibes).includes(ws(F.VIBE_WHERE)));assert.match(F.VIBE_WHERE,/b\.blocker_user_id=\$1::text AND b\.blocked_creator_user_id=v\.creator_user_id\) OR \(b\.blocker_user_id=v\.creator_user_id AND b\.blocked_creator_user_id=\$1::text/);});
test('creator floor is the K5A AUTHOR_FLOOR plus creator_mode',()=>{assert.ok(ws(k5a.people(true)).includes(ws(F.AUTHOR_FLOOR('u','cp','u.id'))));const S=_internal.searchSql({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});assert.match(S.creators,/cp\.creator_mode=TRUE AND/);assert.ok(S.creators.includes(F.AUTHOR_FLOOR('u','cp','u.id')));});
test('content SQL is static, bound ($1 viewer, $2 LIKE query, $3 limit, $4 raw exact query), ordered exact>prefix>contains, returns no score',()=>{const S=_internal.searchSql({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});assert.deepEqual(Object.keys(S).sort(),['articles','channels','creators','groups','posts','products','vibes','workers']);for(const [k,sql] of Object.entries(S)){assert.deepEqual([...new Set(sql.match(/\$\d+/g))].sort(),['$1','$2','$3','$4'],k);
    const col=(k==='groups'||k==='channels')?'s\\.name':k==='products'?'p\\.name':k==='workers'?'w\\.worker_code':'cp\\.public_username';
    assert.doesNotMatch(sql,/\)=\$2\b/,k);assert.match(sql,new RegExp('LOWER\\('+col+'\\)=\\$4'),k);assert.doesNotMatch(sql,/LIKE \$4|\|\|\$4|\$4\|\|/,k);assert.match(sql,new RegExp('LOWER\\('+col+'\\) LIKE \\$2\\|\\|\'%\' ESCAPE'),k);assert.match(sql,/LIKE '%'\|\|\$2\|\|'%' ESCAPE/,k);assert.match(sql,/ORDER BY CASE WHEN .*THEN 0 WHEN .*THEN 1 ELSE 2 END/s,k);assert.doesNotMatch(sql,/\bAS (score|rank)\b/i,k);}
  assert.match(S.articles,/LOWER\(COALESCE\(p\.article_title,''\)\)=\$4/);assert.match(S.articles,/LOWER\(COALESCE\(p\.article_title,''\)\) LIKE '%'\|\|\$2\|\|'%' ESCAPE/);
  assert.match(S.posts,/UPPER\(COALESCE\(p\.post_type,''\)\)<>'ARTICLE'/);assert.match(S.articles,/UPPER\(COALESCE\(p\.post_type,''\)\)='ARTICLE'/);assert.match(S.vibes,/v\.status='published' AND v\.visibility='public' AND v\.deleted_at IS NULL AND v\.vibe_code IS NOT NULL/);});
test('group/channel visibility is the K5A communities predicate; type is a fixed literal; name/slug exact on $4, category contains-only',()=>{assert.ok(ws(k5a.communities).includes(ws(F.SPACE_WHERE)));const S=_internal.searchSql({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});
  assert.match(F.SPACE_WHERE,/s\.is_archived=FALSE AND s\.privacy='PUBLIC' AND s\.slug IS NOT NULL/);assert.match(F.SPACE_WHERE,/kb\.blocker_user_id=\$1::bigint AND kb\.blocked_user_id=s\.owner_user_id\) OR \(kb\.blocker_user_id=s\.owner_user_id AND kb\.blocked_user_id=\$1::bigint/);
  assert.match(S.groups,/WHERE s\.space_type='GROUP' AND/);assert.match(S.channels,/WHERE s\.space_type='CHANNEL' AND/);assert.doesNotMatch(S.groups,/'CHANNEL'/);assert.doesNotMatch(S.channels,/'GROUP'/);
  for(const sql of [S.groups,S.channels]){assert.match(sql,/CASE WHEN LOWER\(s\.name\)=\$4 OR LOWER\(s\.slug\)=\$4 THEN 0 WHEN LOWER\(s\.name\) LIKE \$2\|\|'%' ESCAPE '\\' OR LOWER\(s\.slug\) LIKE \$2\|\|'%' ESCAPE '\\' THEN 1 ELSE 2 END,s\.member_count DESC,s\.slug LIMIT \$3/);assert.doesNotMatch(sql,/LOWER\(s\.category\)=|LOWER\(s\.category\) LIKE \$2\|\|'%'/);assert.doesNotMatch(sql,/SELECT[^]*\bs\.id\b[^]*FROM/);}});
const k5aSrc=fs.readFileSync(path.join(__dirname,'../connect-home-k5a.cjs'),'utf8');
const fnText=(s,start)=>{const i=s.indexOf(start);assert.ok(i>=0,start);let d=0,j=s.indexOf('{',i+start.length-1);for(;j<s.length;j++){if(s[j]==='{')d++;else if(s[j]==='}'&&--d===0)break;}return ws(s.slice(i,j+1));};
test('product visibility is the K5A Shop predicate (publish/archive/timing, vendor, latest moderation, active user, blocks, variant-authoritative stock)',()=>{const shop=ws(k5a.shop);
  assert.ok(shop.includes(ws(F.SHOP_WHERE)));assert.ok(shop.includes(ws(F.SHOP_FROM)));assert.ok(shop.includes(ws(F.SHOP_CREATOR)));
  assert.match(F.SHOP_WHERE,/kb\.blocker_user_id=\$1::bigint AND kb\.blocked_user_id=v\.user_id\) OR \(kb\.blocker_user_id=v\.user_id AND kb\.blocked_user_id=\$1::bigint/);
  const S=_internal.searchSql({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});assert.ok(S.products.includes(F.SHOP_WHERE));assert.ok(S.products.includes(F.SHOP_FROM));
  for(const c of ['p.name','v.business_name','('+F.SHOP_CREATOR+')'])assert.ok(S.products.includes(`LOWER(${c})=$4`),c);assert.ok(S.products.includes(`LOWER(COALESCE(p.category,'')) LIKE '%'||$2||'%'`));assert.ok(!S.products.includes('LOWER(p.category)=$4'));});
test('worker visibility is the K5A Works predicate; worker code/name/service rank exact > prefix > contains and city is contains-only',()=>{const S=_internal.searchSql({connectPostVisibleSql:cpv,k5ePrivateProfileOkSql:ppo});
  assert.ok(ws(k5a.works).includes(ws(F.WORKS_FROM)));assert.ok(ws(k5a.works).includes(ws(F.WORKS_WHERE)));assert.ok(S.workers.includes(F.WORKS_FROM));assert.ok(S.workers.includes(F.WORKS_WHERE));
  assert.match(F.WORKS_WHERE,/LOWER\(TRIM\(w\.kyc_status\)\)='verified'.*LOWER\(TRIM\(w\.skill_status\)\)='verified'.*LOWER\(TRIM\(w\.account_status\)\)='active'.*COALESCE\(w\.active,TRUE\)=TRUE/s);
  assert.match(F.WORKS_WHERE,/w\.user_id IS NULL OR .*ACTIVE.*kb\.blocker_user_id=\$1::bigint AND kb\.blocked_user_id=w\.user_id.*kb\.blocker_user_id=w\.user_id AND kb\.blocked_user_id=\$1::bigint/s);
  for(const c of ['w.worker_code','w.full_name','ps.name']){assert.ok(S.workers.includes(`LOWER(${c})=$4`),c);assert.ok(S.workers.includes(`LOWER(${c}) LIKE $2||'%'`),c);}
  assert.ok(S.workers.includes("LOWER(COALESCE(w.city,'')) LIKE '%'||$2||'%'"));assert.ok(!S.workers.includes('LOWER(w.city)=$4'));assert.doesNotMatch(S.workers,/w\.phone|w\.email|w\.pincode|w\.requested_skill/);
});
test('Shop/Works DTO helpers are verbatim K5A copies',()=>{assert.equal(fnText(src,'const shopRowVisible = (r) => {'),fnText(k5aSrc,'const shopRowVisible = (r) => {'));assert.equal(fnText(src,'function money(value) {'),fnText(k5aSrc,'function money(value) {'));assert.equal(fnText(src,'function rating(value) {'),fnText(k5aSrc,'function rating(value) {'));assert.equal(fnText(src,'function firstImage(list) {'),fnText(k5aSrc,'function firstImage(list) {'));});

// ---- runtime: routing, JS re-checks, refs issued only for visible rows, DTO allow-lists
const ROWS={
  creators:[{public_username:'k5b_maker',display_name:'Maker',avatar:'https://cdn.example/a.png',headline:'Potter',is_active:true,account_status:'ACTIVE',discoverable:true,user_id:991,email:'m@x.test'},
    {public_username:'k5b_gone',display_name:'Gone',avatar:'',headline:'',is_active:true,account_status:'SUSPENDED',discoverable:true}],
  posts:[{internal_key:'7001',post_type:'POST',content:'hello clay',post_status:'PUBLISHED',audience_scope:'EVERYONE',has_media:true,display_name:'Maker',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true},
    {internal_key:'7002',post_type:'POST',content:'fans only',post_status:'PUBLISHED',audience_scope:'EVERYONE',subscribers_only:true,public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true},
    {internal_key:'7003',post_type:'POST',content:'followers',post_status:'PUBLISHED',audience_scope:'FOLLOWERS',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true},
    {internal_key:'7004',post_type:'ARTICLE',content:'not a post',post_status:'PUBLISHED',audience_scope:'EVERYONE',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true}],
  articles:[{internal_key:'8001',post_type:'ARTICLE',content:'long body',article_title:'Glazing 101',article_excerpt:'short',cover:'https://cdn.example/c.jpg',post_status:'PUBLISHED',audience_scope:'EVERYONE',display_name:'Maker',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true},
    {internal_key:'8002',post_type:'ARTICLE',content:'draft',article_title:'Draft',post_status:'DRAFT',audience_scope:'EVERYONE',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true}],
  vibes:[{vibe_code:'VB-K5BTEST01',caption:'spin',cover_url:'javascript:alert(1)',display_name:'Maker',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true,creator_user_id:'991'},
    {vibe_code:'3f2504e0-4f89-11d3-9a0c-0305e82c3301',caption:'uuid code',public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',discoverable:true}],
  people:[{public_username:'k5b_maker',display_name:'Maker',avatar:'',headline:'Potter'}],
};
const SP={space_type:'GROUP',category:'Pottery',member_count:12,is_archived:false,privacy:'PUBLIC',is_active:true,account_status:'ACTIVE',id:5501,owner_user_id:991};
ROWS.groups=[{...SP,name:'K5B Guild',slug:'k5b-guild'},{...SP,space_type:'CHANNEL',name:'K5B Chan',slug:'k5b-chan-leak'},{...SP,name:'Archived',slug:'k5b-archived',is_archived:true},
  {...SP,name:'Private',slug:'k5b-private',privacy:'PRIVATE'},{...SP,name:'Suspended owner',slug:'k5b-susp',account_status:'SUSPENDED'},{...SP,name:'Inactive owner',slug:'k5b-inact',is_active:false},{...SP,name:'Bad slug',slug:'Bad_Slug'}];
ROWS.channels=[{...SP,space_type:'CHANNEL',name:'K5B Channel',slug:'k5b-channel',category:'',member_count:-3},{...SP,name:'K5B Group',slug:'k5b-group-leak'}];
const PR={name:'K5B Mug',category:'Pottery',price:'450.00',mrp:'500.00',image_urls:['https://cdn.example/m.jpg'],status:'published',archived_at:null,published_at:null,vendor_status:'active',moderation_status:null,
  store_name:'Asha Clay',creator_public_username:'k5b_maker',is_active:true,account_status:'ACTIVE',vendor_profile_id:6602,user_id:991,stock:5};
ROWS.products=[{...PR,internal_key:'6601'},{...PR,internal_key:'6603',status:'draft'},{...PR,internal_key:'6604',archived_at:'2026-01-01T00:00:00Z'},{...PR,internal_key:'6605',published_at:new Date(Date.now()+864e5).toISOString()},
  {...PR,internal_key:'6606',vendor_status:'suspended'},{...PR,internal_key:'6607',moderation_status:'PENDING'},{...PR,internal_key:'6608',account_status:'SUSPENDED'},{...PR,internal_key:'6610',is_active:false},
  {...PR,internal_key:'6609',name:'K5B Bowl',price:'450',mrp:'400',image_urls:'["javascript:alert(1)"]',creator_public_username:'12345',category:'',moderation_status:' approved '}];
const WK={worker_code:'WRK-K5B_01',full_name:'K5B Worker',city:'Warangal',rating:'4.7',completed_jobs:9,primary_service:'Kiln Repair',kyc_status:'verified',skill_status:'verified',worker_account_status:'active',worker_active:true,has_user:true,is_active:true,user_account_status:'ACTIVE',user_id:991,phone:'9000000000',pincode:'506002'};
ROWS.workers=[{...WK},{...WK,worker_code:'550e8400-e29b-41d4-a716-446655440000',full_name:'UUID Worker'},{...WK,worker_code:'WRK-K5B_BADKYC',full_name:'KYC Pending',kyc_status:'pending'},
  {...WK,worker_code:'WRK-K5B_BADSKILL',full_name:'Skill Pending',skill_status:'pending'},{...WK,worker_code:'WRK-K5B_INACTIVE',full_name:'Inactive Worker',worker_active:false},
  {...WK,worker_code:'WRK-K5B_SUSPUSER',full_name:'Suspended User Worker',user_account_status:'SUSPENDED'}];
const pick=(sql)=>/FROM vendor_products p/.test(sql)?'products':/FROM works_workers w/.test(sql)?'workers':/howdi_connect_social_spaces/.test(sql)?(/space_type='CHANNEL'/.test(sql)?'channels':'groups'):/FROM vibes v/.test(sql)?'vibes':/creator_mode=TRUE/.test(sql)?'creators':/='ARTICLE' AND/.test(sql)?'articles':/<>'ARTICLE' AND/.test(sql)?'posts':'people';
function harness({viewer=null,issueRefs:ir,cpvFn=cpv}={}){
  const calls=[],refCalls=[];
  const issueRefs=ir||(async(type,keys)=>{refCalls.push([type,keys]);return new Map(keys.map((k,i)=>[String(k),({ARTICLE:'ART',PRODUCT:'PRD'}[type]||'PST')+'-'+String(i+1).padStart(12,'A')]));});
  const svc=createGlobalSearchK5B({pool:{query:async(sql,params)=>{calls.push({kind:pick(sql),params});return {rows:ROWS[pick(sql)]};}},getSessionUserFromRequest:async()=>viewer,sendJSON:(res,status,body)=>{res.status=status;res.body=body;},k5ePrivateProfileOkSql:ppo,connectPostVisibleSql:cpvFn,issueRefs});
  const get=async(qs)=>{const res={headersSent:false,setHeader(){}};const handled=await svc.handle({method:'GET'},res,new URL('http://x/api/search?'+qs));return {handled,...res};};
  return {get,calls,refCalls};
}
const keysOf=(o)=>Object.keys(o).sort();
test('every supported type is routed; unknown type is INVALID_TYPE',async()=>{const h=harness();for(const t of SEARCH_TYPES){const r=await h.get('q=k5b&type='+t);assert.equal(r.status,200,t);assert.equal(r.body.type,t);assert.equal(r.body.status,'success');}
  for(const t of ['bogus','users','PEOPLEX','services','']){const r=await h.get('q=k5b&type='+encodeURIComponent(t));if(t===''){assert.equal(r.status,200);continue;}assert.equal(r.status,400,t);assert.equal(r.body.code,'INVALID_TYPE');}
  assert.equal((await harness().get('q=k&type=posts')).body.code,'INVALID_QUERY');assert.equal((await harness().get('q='+'x'.repeat(81)+'&type=vibes')).body.code,'INVALID_QUERY');});
test('query and limit are bound; raw exact and LIKE-escaped forms are passed separately; limit clamps 1..20',async()=>{const B=String.fromCharCode(92),raw='ab%_'+B+'x',esc='ab'+B+'%'+B+'_'+B+B+'x';assert.equal(raw,'ab%_\\x');assert.equal(esc,'ab\\%\\_\\\\x');
  const h=harness({viewer:{id:42}});for(const t of ['creators','posts','articles','vibes','groups','channels','products','workers']){h.calls.length=0;await h.get('q='+encodeURIComponent('Ab%_\\x')+'&type='+t+'&limit=500');assert.deepEqual(h.calls[0].params,[42,esc,20,raw],t);}
  h.calls.length=0;await h.get('q='+encodeURIComponent('Ab%_\\x')+'&type=people&limit=7');assert.deepEqual(h.calls[0].params,[esc,42,7,raw]);
  h.calls.length=0;await h.get('q=ab&type=vibes&limit=0');assert.equal(h.calls[0].params[2],1);});
test('inactive session viewer is treated as guest for content search',async()=>{const h=harness({viewer:{id:42,account_status:'SUSPENDED'}});await h.get('q=ab&type=creators');assert.equal(h.calls[0].params[0],0);});
test('creators DTO allow-list and JS floor re-check',async()=>{const r=await harness().get('q=k5b&type=creators');assert.equal(r.body.results.length,1);const c=r.body.results[0];assert.deepEqual(keysOf(c),['avatar_url','display_name','headline','public_username','route','type']);assert.equal(c.type,'creator');assert.equal(c.route,'/@k5b_maker');});
test('posts: guest JS gate drops subscriber/audience/article rows; PST refs issued only for visible rows',async()=>{const h=harness();const r=await h.get('q=k5b&type=posts');assert.deepEqual(h.refCalls,[['POST',['7001']]]);assert.equal(r.body.results.length,1);const p=r.body.results[0];
  assert.deepEqual(keysOf(p),['display_name','has_media','public_key','public_username','route','text_excerpt','type']);assert.match(p.public_key,/^PST-[0-9A-F]{12}$/);assert.equal(p.route,'/posts/'+p.public_key);assert.equal(p.has_media,true);});
test('posts: signed-in viewer keeps SQL-approved audience rows (connectPostVisibleSql decides in SQL)',async()=>{const h=harness({viewer:{id:5}});await h.get('q=k5b&type=posts');assert.deepEqual(h.refCalls,[['POST',['7001','7003']]]);});
test('articles: ART refs only for visible ARTICLE rows; safe DTO with cover_url',async()=>{const h=harness();const r=await h.get('q=glaz&type=articles');assert.deepEqual(h.refCalls,[['ARTICLE',['8001']]]);const a=r.body.results[0];
  assert.deepEqual(keysOf(a),['cover_url','display_name','public_key','public_username','route','text_excerpt','title','type']);assert.match(a.public_key,/^ART-/);assert.equal(a.title,'Glazing 101');assert.equal(a.text_excerpt,'short');assert.equal(a.cover_url,'https://cdn.example/c.jpg');});
test('a ref with the wrong prefix is never returned',async()=>{const r=await harness({issueRefs:async(t,keys)=>new Map(keys.map(k=>[String(k),'ART-AAAAAAAAAAAA']))}).get('q=k5b&type=posts');assert.equal(r.body.results.length,0);});
test('vibes: vibe_code only, uuid-shaped codes dropped, unsafe cover dropped',async()=>{const r=await harness().get('q=spin&type=vibes');assert.equal(r.body.results.length,1);const v=r.body.results[0];assert.deepEqual(keysOf(v),['caption','cover_url','display_name','public_key','public_username','route','type']);assert.equal(v.public_key,'VB-K5BTEST01');assert.equal(v.cover_url,null);assert.equal(v.route,'/vibes/VB-K5BTEST01');});
test('no content DTO carries an internal/private key or value',async()=>{for(const t of SEARCH_TYPES){const r=await harness().get('q=k5b&type='+t);const s=JSON.stringify(r.body.results);for(const x of r.body.results)for(const k of Object.keys(x))assert.ok(!FORBIDDEN_KEY_RE.test(k),t+':'+k);assert.doesNotMatch(s,/7001|7002|8001|991|5501|6601|6602|6609|9000000000|506002|m@x\.test|[0-9a-f]{8}-[0-9a-f]{4}-/i,t);assert.doesNotMatch(s,/"(PUBLIC|PRIVATE|ACTIVE|SUSPENDED|GROUP|CHANNEL)"/,t);}});
test('groups: K5A slug validation + JS re-check drop archived/non-public/inactive/suspended/channel rows; safe DTO',async()=>{const r=await harness().get('q=k5b&type=groups');assert.deepEqual(r.body.results,[{type:'group',public_key:'k5b-guild',name:'K5B Guild',category:'Pottery',member_count:12,route:'/groups/k5b-guild'}]);});
test('products: JS Shop gate + active user re-check; PRD refs issued only for visible rows; explicit DTO',async()=>{const h=harness();const r=await h.get('q=k5b&type=products');assert.deepEqual(h.refCalls,[['PRODUCT',['6601','6609']]]);
  assert.deepEqual(r.body.results[0],{type:'product',public_key:'PRD-AAAAAAAAAAA1',title:'K5B Mug',image_url:'https://cdn.example/m.jpg',price:450,compare_at_price:500,currency:'INR',category:'Pottery',store:{name:'Asha Clay',public_username:'k5b_maker'},route:'/shop/products/PRD-AAAAAAAAAAA1'});
  assert.deepEqual(r.body.results[1],{type:'product',public_key:'PRD-AAAAAAAAAAA2',title:'K5B Bowl',image_url:null,price:450,compare_at_price:null,currency:'INR',category:null,store:{name:'Asha Clay',public_username:null},route:'/shop/products/PRD-AAAAAAAAAAA2'});
  assert.equal((await harness({issueRefs:async(t,keys)=>new Map(keys.map(k=>[String(k),'PST-AAAAAAAAAAAA']))}).get('q=k5b&type=products')).body.results.length,0);});
test('workers: K5A eligibility re-check + public worker_code DTO; invalid/private identities never leak',async()=>{const r=await harness().get('q=k5b&type=workers');assert.equal(r.status,200);assert.equal(r.body.results.length,1);const w=r.body.results[0];
  assert.deepEqual(w,{type:'worker',public_key:'WRK-K5B_01',display_name:'K5B Worker',skill:'Kiln Repair',service_area:'Warangal',rating:4.7,completed_jobs:9,verified:true,route:'/works/workers/WRK-K5B_01'});
  assert.deepEqual(keysOf(w),['completed_jobs','display_name','public_key','rating','route','service_area','skill','type','verified']);assert.doesNotMatch(JSON.stringify(r.body.results),/991|9000000000|506002|550e8400|pending|SUSPENDED/);
});
test('channels: never returns groups; safe DTO with null category and non-negative member_count',async()=>{const r=await harness().get('q=k5b&type=channels');assert.deepEqual(r.body.results,[{type:'channel',public_key:'k5b-channel',name:'K5B Channel',category:null,member_count:0,route:'/channels/k5b-channel'}]);});
test('content search fails closed when dependencies are not injected',async()=>{const svc=createGlobalSearchK5B({pool:{query:async()=>({rows:[]})},getSessionUserFromRequest:async()=>null,sendJSON:(res,s,b)=>{res.status=s;res.body=b;},k5ePrivateProfileOkSql:ppo});for(const t of ['creators','posts','articles','vibes','groups','channels','products','workers']){const res={};await svc.handle({method:'GET'},res,new URL('http://x/api/search?q=ab&type='+t));assert.equal(res.status,503,t);}});
test('server injects connectPostVisibleSql and K5A issueRefs after K5A is constructed',()=>{const s=fs.readFileSync(path.join(__dirname,'../server.js'),'utf8');const a=s.indexOf('const connectHomeK5A = require("./connect-home-k5a.cjs")'),b=s.indexOf('createGlobalSearchK5B({');assert.ok(a>0&&b>a);assert.match(s.slice(b,b+300),/connectPostVisibleSql, issueRefs: connectHomeK5A\._internal\.issueRefs/);});
