import test from "node:test";
import assert from "node:assert/strict";
import {GLOBAL_SEARCH_TYPES,GLOBAL_SEARCH_SCOPE_OPTIONS,normalizeGlobalSearchQuery,isGlobalSearchQueryValid,typesForGlobalSearchScope,safeGlobalSearchRoute,normalizeGlobalSearchResult,fetchGlobalSearchK5B} from "./globalSearchK5B.js";

test("query contract matches K5B bounds and normalization",()=>{assert.equal(normalizeGlobalSearchQuery("  A\u00a0  B  "),"A B");assert.equal(isGlobalSearchQueryValid("a"),false);assert.equal(isGlobalSearchQueryValid("ab"),true);assert.equal(isGlobalSearchQueryValid("x".repeat(80)),true);assert.equal(isGlobalSearchQueryValid("x".repeat(81)),false);});
test("UI scopes request only implemented public K5B types",()=>{assert.deepEqual(GLOBAL_SEARCH_TYPES,["people","creators","posts","articles","vibes","groups","channels","products","workers","teachers"]);for(const blocked of ["services","courses","storefronts"])assert.equal(GLOBAL_SEARCH_TYPES.includes(blocked),false);assert.deepEqual(typesForGlobalSearchScope("learn"),["teachers"]);assert.deepEqual(typesForGlobalSearchScope("shop"),["products"]);assert.equal(GLOBAL_SEARCH_SCOPE_OPTIONS[0].value,"all");});
test("route allow-list accepts K5B canonical routes and rejects unsafe/internal URLs",()=>{for(const route of ["/@asha.maker","/posts/PST-AAAAAAAAAAAA","/articles/ART-123456789ABC","/vibes/VB-K5B_01","/groups/k5b-guild","/channels/k5b-news","/shop/products/PRD-AAAAAAAAAAAA","/works/workers/WRK-K5B_01"])assert.equal(safeGlobalSearchRoute(route),route);for(const route of ["javascript:alert(1)","https://evil.test/x","/learn/course/550e8400-e29b-41d4-a716-446655440000","/shop/products/6601","/works/workers/123456789","/works/workers/550e8400-e29b-41d4-a716-446655440000","/groups/Bad_Slug"])assert.equal(safeGlobalSearchRoute(route),null);});
test("normalizer emits an explicit UI allow-list and drops private/internal fields",()=>{const x=normalizeGlobalSearchResult({type:"teacher",public_key:"HOWDI-TCH-ABCD1234",public_username:"asha_teacher",display_name:"Asha",avatar_url:"https://cdn.example/t.png",headline:"Crochet mentor",course_count:2,route:"/@asha_teacher",id:99,email:"x@y.test",phone:"9999999999",city:"Secret"},"teachers");assert.deepEqual(x,{key:"teacher:/@asha_teacher",type:"teacher",type_label:"Teacher",icon:"🎓",title:"Asha",subtitle:"@asha_teacher · Crochet mentor",meta:"2 public courses",image_url:"https://cdn.example/t.png",route:"/@asha_teacher",public_key:"HOWDI-TCH-ABCD1234",public_username:"asha_teacher"});assert.doesNotMatch(JSON.stringify(x),/x@y|999999|Secret/);});
test("fanout is round-robin by type, tolerates partial failures and never calls blocked types",async()=>{const calls=[];const fake=async url=>{calls.push(url);const u=new URL(url,"http://x");const type=u.searchParams.get("type");if(type==="workers")return {ok:false,json:async()=>({status:"error"})};const results=type==="people"?[{type:"person",public_username:"asha",display_name:"Asha",route:"/@asha"},{type:"person",public_username:"bina",display_name:"Bina",route:"/@bina"}]:[{type:"product",public_key:"PRD-AAAAAAAAAAAA",title:"Asha Bag",price:500,currency:"INR",route:"/shop/products/PRD-AAAAAAAAAAAA"}];return {ok:true,json:async()=>({status:"success",type,results})};};const out=await fetchGlobalSearchK5B({fetchImpl:fake,apiBase:"http://api.test/",query:" Asha Bag ",types:["people","workers","products","courses"],limit:99,maxResults:10});assert.deepEqual(out.requested_types,["people","workers","products"]);assert.deepEqual(out.failed_types,["workers"]);assert.deepEqual(out.results.map(x=>x.title),["Asha","Asha Bag","Bina"]);assert.equal(calls.length,3);assert.ok(calls.every(x=>x.includes("q=Asha%20Bag")));assert.ok(calls.every(x=>x.includes("limit=20")));assert.equal(calls.some(x=>x.includes("courses")),false);});
test("invalid query performs no network requests",async()=>{let calls=0;const out=await fetchGlobalSearchK5B({fetchImpl:async()=>{calls++;throw new Error("should not run")},query:"x"});assert.equal(calls,0);assert.deepEqual(out.results,[]);assert.deepEqual(out.requested_types,[]);});
