import { useCallback, useEffect, useRef, useState } from 'react';
import './rides.css';

const BASE = '/api/v8/rides';
export const rupees = n => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format((n || 0) / 100);
export const rideWhen = value => new Date(value).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
export function RidePanel({ id, title, children }) { return <section className="ride-panel" data-screen={id}><div className="ride-eyebrow">{id} · Proposed extension</div><h2>{title}</h2>{children}<small className="ride-gate">Draft visual — awaiting Bhaskar review · implementation awaiting walkthrough</small></section>; }
export function RideField({ label, children }) { return <label className="ride-field"><span>{label}</span>{children}</label>; }
export function RideSafety() { return <aside className="ride-safety"><strong>Safety & support</strong><p>For immediate danger in India, call <a href="tel:112">112</a>. HOWDI Preview does not dispatch emergency help. Ride support goes to the local staff queue.</p><p>No live GPS, SMS or real money. Production licence, permit, insurance and safety gates remain closed.</p></aside>; }
export default function Rides({ api, path = '', nav }) {
  const [config, setConfig] = useState(null), [data, setData] = useState(null), [error, setError] = useState(''), [message, setMessage] = useState(''), [busy, setBusy] = useState(false);
  const [online, setOnline] = useState(navigator.onLine), lock = useRef(false);
  const load = useCallback(async () => { const [c, d] = await Promise.all([api('GET', BASE + '/config'), api('GET', BASE)]); if (!c.ok || !d.ok) { setError(c.json?.message || d.json?.message); return; } setConfig(c.json); setData(d.json); }, [api]);
  useEffect(() => { load(); const timer = setInterval(load, 15000); const on = () => { setOnline(navigator.onLine); if (navigator.onLine) load(); }; window.addEventListener('online', on); window.addEventListener('offline', on); return () => { clearInterval(timer); window.removeEventListener('online', on); window.removeEventListener('offline', on); }; }, [load]);
  const call = async (method, url, body) => {
    if (lock.current) return null; lock.current = true; setBusy(true); setError(''); setMessage('');
    try { const signal = AbortSignal.timeout(15000); const r = await api(method, url, body, { signal }); if (!r.ok) { setError(signal.aborted ? 'TIMEOUT · No confirmation received. Retry the same request safely; do not create another booking.' : `${r.json?.code || (r.status ? 'ERROR' : 'OFFLINE')} · ${r.json?.message || 'Request failed. Retry safely.'}`); return null; } setMessage(r.json.duplicate ? 'Duplicate request recovered. No second booking or charge.' : 'Saved to the preview database.'); await load(); return r.json; }
    finally { setBusy(false); lock.current = false; }
  };
  const sub = path.replace(/^\//, '').replace(/^rides\/?/, ''), selected = data?.rides.find(r => r.code === sub);
  return <div className="rides"><div className="ride-banner">LOCAL SANDBOX · PREVIEW / TEST ONLY</div><header className="ride-header"><div><span className="ride-eyebrow">HOWDI Move</span><h1>Your next ride, with HOWDI.</h1><p>Book now or schedule · verified preview rides · {config?.zone || 'Pilot preview'}</p></div><span className="ride-symbol" aria-hidden="true">↗</span></header>
    <nav className="ride-tabs" aria-label="Rides"><button onClick={() => nav('rides')}>Book now</button><button onClick={() => nav('rides/trips')}>My rides</button><button onClick={() => nav('rides/apply')}>Drive with HOWDI</button>{data?.applications.some(a => a.state === 'approved') && <button onClick={() => nav('rides/desk')}>Rider desk</button>}</nav>
    {!online && <p className="ride-alert" role="alert">Offline — last confirmed status is shown. Reconnect before changing a ride.</p>}
    {error && <p className="ride-alert" role="alert">{error} <button onClick={() => { setError(''); load(); }}>Retry</button></p>}{message && <p className="ride-notice" role="status">{message}</p>}
    {!config || !data ? <RidePanel id="RIDE-002" title={error ? 'Rides unavailable' : 'Loading rides…'}><p>{error ? 'Sign in and check that the local preview is enabled.' : 'Checking the pilot and your saved rides.'}</p></RidePanel> : <fieldset className="ride-body" disabled={busy || !online} aria-busy={busy}>
      {busy && <p role="status">Saving… Please wait.</p>}
      {sub === 'apply' ? <Application applications={data.applications} call={call} zone={config.zone} /> : sub === 'desk' ? <DriverDesk data={data} call={call} nav={nav} /> : selected ? <Trip ride={selected} call={call} /> : sub.startsWith('HR-') ? <RidePanel id="RIDE-002" title="Ride unavailable"><p>Permission denied or ride not found. Open My rides using the account that booked or accepted this trip.</p></RidePanel> : sub === 'trips' ? <RidePanel id="RIDE-002" title="Your rides"><RideList rides={data.rides} nav={nav} /><button onClick={load}>Refresh status</button></RidePanel> : <Quote config={config} call={call} nav={nav} />}
      <details className="ride-panel"><summary>Preview notifications ({data.notices.length})</summary>{data.notices.map((n, i) => <p key={i}><b>{n.ref}</b> · {n.message}</p>)}{!data.notices.length && <p>No notifications yet.</p>}</details>
    </fieldset>}
    <RideSafety />
  </div>;
}
function Quote({ config, call, nav }) {
  const [form,setForm]=useState({mode:'instant',zone:config.zone,pickup:'',destination:'',scheduled_at:'',vehicle_class:'Auto',accessibility:'none',payment:'cash'});
  const [q,setQ]=useState(null),[confirmed,setConfirmed]=useState(false),key=useRef(crypto.randomUUID());
  const modes=config.modes || [],selected=modes.find(m=>m.name===form.vehicle_class);
  const change=(name,value)=>{setForm(f=>({...f,[name]:value}));setQ(null);setConfirmed(false);};
  const estimate=async e=>{e.preventDefault();const body={...form};if(form.mode==='scheduled')body.scheduled_at=new Date(form.scheduled_at).toISOString();else delete body.scheduled_at;const r=await call('POST',BASE+'/quote',body);if(r){setQ(r);key.current=crypto.randomUUID();setConfirmed(false);}};
  return <div className="ride-grid"><RidePanel id="RIDE-001" title="Where are you going?">
    <div className="ride-booking-mode" role="group" aria-label="Booking time"><button className={form.mode==='instant'?'ride-primary':''} aria-pressed={form.mode==='instant'} onClick={()=>change('mode','instant')}>Book now</button><button aria-pressed={form.mode==='scheduled'} onClick={()=>change('mode','scheduled')}>Schedule</button></div>
    <p>{form.mode==='instant'?'Find an available verified driver in this local test pilot. No real dispatch.':'Plan 30 minutes to 7 days ahead. Scheduled trips remain subject to driver acceptance.'}</p>
    <div className="ride-mode-grid" role="group" aria-label="Ride class">{modes.map(m=><button key={m.name} type="button" aria-pressed={form.vehicle_class===m.name} className={form.vehicle_class===m.name?'ride-mode-selected':''} onClick={()=>change('vehicle_class',m.name)}><b>{m.name}</b><small>{m.enabled?'Preview available':'Unavailable'}</small></button>)}</div>
    <p className={selected?.enabled?'ride-notice':'ride-alert'} role="status">{selected?.reason || 'Checking class gates…'}</p>
    {!selected?.enabled && <p>{form.vehicle_class==='Women Special'?'Women Special is not open. There will be no general-driver fallback. Choose a different class only if you want to.':'This class cannot take bookings until its preview gate is enabled.'}</p>}
    <form onSubmit={estimate}>
      <RideField label="Pickup meeting point"><input required maxLength={300} value={form.pickup} onChange={e=>change('pickup',e.target.value)} placeholder="Building, entrance or landmark" /></RideField>
      <RideField label="Destination meeting point"><input required maxLength={300} value={form.destination} onChange={e=>change('destination',e.target.value)} placeholder="Where would you like to go?" /></RideField>
      <p className="ride-location-note">Location denied or unavailable? Type your meeting point. This preview does not request GPS permission or collect live location.</p>
      {form.mode==='scheduled' && <RideField label="Schedule date & time (your device time)"><input required type="datetime-local" value={form.scheduled_at} onChange={e=>change('scheduled_at',e.target.value)} /></RideField>}
      <RideField label="Accessibility need"><select value={form.accessibility} onChange={e=>change('accessibility',e.target.value)}><option value="none">No additional requirement</option><option value="step_free">Verified step-free vehicle required</option></select></RideField>
      <RideField label="Payment"><select value={form.payment} onChange={e=>change('payment',e.target.value)}><option value="cash">Cash (test collection)</option><option value="hpay_test">HPay Test</option></select></RideField>
      <button className="ride-primary" disabled={!selected?.enabled}>Review fare & availability</button>
    </form>
  </RidePanel><RidePanel id={form.mode==='scheduled'?'RIDE-013':'RIDE-002'} title="Know your fare before you confirm">
    {q?<><div className="ride-fare"><span>Estimated total · Test</span><strong>{rupees(q.fare.total)}</strong></div><dl><dt>Base fare</dt><dd>{rupees(q.fare.base)}</dd><dt>{q.mode==='instant'?'Book now surcharge':'Scheduled pickup'}</dt><dd>{rupees(q.fare.scheduled)}</dd><dt>Service</dt><dd>{rupees(q.fare.service)}</dd></dl><p>{q.fare.basis}</p><p>{q.cancellation}</p><p>Quote expires {rideWhen(q.expires_at)}. Availability is rechecked when offering and starting a trip.</p><label className="ride-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} />I reviewed the fare and cancellation terms.</label><button className="ride-primary" disabled={!confirmed || !selected?.enabled} onClick={async()=>{const r=await call('POST',BASE+'/bookings',{quote_code:q.code,request_key:key.current});if(r?.ride)nav('rides/'+r.ride.code);}}>{q.mode==='instant'?'Confirm Book now':'Confirm scheduled request'}</button></>:<><div className="ride-route"><span>01 · Your pickup</span><i /><span>02 · Your destination</span></div><p>Itemised preview estimate. No hidden class change, automatic fallback or real charge.</p><p>Exact pickup and vehicle plate stay private until both participants confirm the disclosure. Check the plate, then share your pickup PIN in person.</p></>}
  </RidePanel></div>;
}

function RideList({ rides, nav }) { return rides.length ? <div className="ride-list">{rides.map(r => <button key={r.code} onClick={() => nav('rides/' + r.code)}><strong>{r.code}</strong><span>{r.quote.vehicle_class} · {r.state.replaceAll('_', ' ')} · {rideWhen(r.quote.scheduled_at)}</span><span>{rupees(r.quote.fare.total)} · {r.quote.payment === 'cash' ? 'Cash' : 'HPay Test'}</span></button>)}</div> : <p>No rides yet. Your scheduled trips will appear here.</p>; }
const appForm = a => Object.fromEntries(Object.entries(a?.details || {}).map(([k,v]) => [k, k.endsWith('_until') && Number.isFinite(Date.parse(v)) ? new Date(Date.parse(v) - new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16) : v]));
function Application({ applications, call, zone }) {
  const [cls, setCls] = useState('Auto'), a = applications.find(a => a.vehicle_class === cls), [form, setForm] = useState(appForm(a)), [saved, setSaved] = useState(a?.code), [kind, setKind] = useState('identity');
  const editable = !a || ['draft', 'info_requested', 'rejected', 'expired'].includes(a.state);
  return <RidePanel id="RIDE-005" title="Drive with HOWDI"><p>Each vehicle class needs its own approval. Worker approval does not permit passenger transport.</p><RideField label="Vehicle class"><select value={cls} onChange={e => { setCls(e.target.value); const app = applications.find(a => a.vehicle_class === e.target.value); setForm(appForm(app)); setSaved(app?.code); }}><option>Auto</option><option>Cab</option></select></RideField><p><b>Status: {a?.state || 'Not started'}</b> · {zone}</p>{a?.reason && <p className="ride-notice">Staff: {a.reason}</p>}
    <fieldset disabled={!editable}><form onSubmit={async e => { e.preventDefault(); const r = await call('PUT', BASE + '/application', { ...form, vehicle_class: cls, ...Object.fromEntries(['licence_until','permit_until','insurance_until'].map(k => [k, form[k] ? new Date(form[k]).toISOString() : ''])) }); if (r) setSaved(r.application.code); }}>
      {['plate', 'licence_until', 'permit_until', 'insurance_until'].map(k => <RideField key={k} label={k.replaceAll('_', ' ')}><input required value={form[k] || ''} type={k.endsWith('until') ? 'datetime-local' : 'text'} onChange={e => setForm({ ...form, [k]: e.target.value })} /></RideField>)}
      <RideField label="Vehicle accessibility"><select value={form.accessibility || 'none'} onChange={e => setForm({ ...form, accessibility: e.target.value })}><option value="none">Standard</option><option value="step_free">Step-free (staff evidence check required)</option></select></RideField>
      {['age_confirmed', 'declaration'].map(k => <label className="ride-check" key={k}><input type="checkbox" checked={!!form[k]} onChange={e => setForm({ ...form, [k]: e.target.checked })} />{k === 'age_confirmed' ? 'I am at least 18.' : 'These documents and vehicle details are accurate for preview verification.'}</label>)}<button>Save draft</button></form>
      {saved && <><h3>Private verification documents</h3><p>Saved: {a?.document_kinds?.join(", ") || "none yet"}</p><p>Use synthetic test documents only in this local sandbox. Save changes before submitting.</p><RideField label="Document type"><select value={kind} onChange={e => setKind(e.target.value)}>{['identity', 'licence', 'registration', 'permit', 'insurance', 'safety'].map(k => <option key={k}>{k}</option>)}</select></RideField><RideField label="PNG/JPEG document (up to 1 MB)"><input type="file" accept="image/png,image/jpeg" onChange={async e => { const f = e.target.files?.[0]; if (!f) return; const image = await new Promise(resolve => { const r = new FileReader(); r.onload = () => resolve(r.result); r.readAsDataURL(f); }); await call('POST', BASE + `/applications/${saved}/document`, { kind, image }); }} /></RideField><button className="ride-primary" onClick={() => call('POST', BASE + `/applications/${saved}/submit`, {})}>Submit for staff verification</button></>}
    </fieldset></RidePanel>;
}
function DriverDesk({ data, call, nav }) { return <><RidePanel id="RIDE-006" title="Rider desk"><p>Passenger trips only. Eligibility is rechecked for every offer and start.</p>{data.applications.map(a => <div key={a.code} className="ride-notice"><b>{a.vehicle_class} · {a.state}</b><p>{a.zone} · {a.eligible_now ? 'Documents valid now' : 'Not eligible now'}</p><button disabled={!a.eligible_now} onClick={() => call('POST', BASE + `/applications/${a.code}/availability`, { available: !a.available })}>{a.available ? 'Go unavailable' : 'Go available'}</button></div>)}<h3>Ride offers</h3>{!data.offers.length && <p>No eligible offers. Check availability, class, zone and document expiry.</p>}{data.offers.map(r => <article className="ride-offer" key={r.code}><h3>{r.code}</h3><p>{r.quote.zone} · {r.quote.vehicle_class} · {r.quote.mode === "instant" ? "Book now" : rideWhen(r.quote.scheduled_at)}</p>{r.offer_expires_at && <OfferClock until={r.offer_expires_at} />}<p>{rupees(r.quote.fare.total)} · {r.quote.accessibility} · precise addresses hidden</p><button className="ride-primary" onClick={async () => { const x = await call('POST', BASE + `/${r.code}/accept`, {}); if (x) nav('rides/' + r.code); }}>Accept trip</button><button onClick={() => call('POST', BASE + `/${r.code}/decline`, {})}>Decline</button></article>)}</RidePanel><RidePanel id="RIDE-008" title="Passenger trips & earnings"><RideList rides={data.rides.filter(r => r.side === 'driver')} nav={nav} /></RidePanel></>; }
function Trip({ ride: r, call }) {
  const [agree, setAgree] = useState(false), [pin, setPin] = useState(''), [cancel, setCancel] = useState(false), [reason, setReason] = useState(''), [kind, setKind] = useState('support'), [stars, setStars] = useState(5);
  const driver = r.side === 'driver', action = (name, body = {}) => call('POST', `${BASE}/${r.code}/${name}`, body), consented = driver ? r.driver_consent : r.customer_consent;
  return <div className="ride-grid"><RidePanel id={driver ? 'RIDE-007' : 'RIDE-002'} title={r.matching === 'no_eligible_driver' ? 'No eligible driver' : r.state.replaceAll('_', ' ')}><b className="ride-code">{r.code}</b>{r.quote.mode === "instant" && <p>Book now · local preview</p>}{r.state === "requested" && r.offer_expires_at && <OfferClock until={r.offer_expires_at} />}<p>{rideWhen(r.quote.scheduled_at)} · {r.quote.vehicle_class}</p><p>{driver ? `Customer @${r.customer}` : r.driver ? `Driver @${r.driver}` : r.matching === 'no_eligible_driver' ? 'No eligible driver is available for this class, area and accessibility need. No automatic fallback. Wait or cancel and deliberately create another request.' : 'No driver has accepted yet. You may wait, refresh or cancel.'}</p><p>{rupees(r.quote.fare.total)} · {r.quote.payment === 'cash' ? 'Cash test collection' : 'HPay Test'}</p>
    {r.pickup && <div className="ride-route"><span>Pickup · {r.pickup}</span><i /><span>Destination · {r.destination}</span></div>}
    {r.state === 'accepted' && !consented && <div data-screen="RIDE-009"><h3>Confirm exactly what you share</h3><ul>{r.consent_fields.map(f => <li key={f}>{f.replaceAll('_', ' ')}</li>)}</ul><p>Shared only with the other participant for this ride. Phones remain private. No GPS or trusted-contact sharing is enabled. Consent events retain field names only. Contact support for data deletion review.</p><label className="ride-check"><input type="checkbox" checked={agree} onChange={e => setAgree(e.target.checked)} />I affirm these fields for this ride.</label><button disabled={!agree} className="ride-primary" onClick={() => action('consent', { fields: r.consent_fields })}>Confirm field disclosure</button></div>}
    {r.state === 'accepted' && consented && !r.plate && <p>Waiting for the other participant to confirm. Plate and driver pickup instructions stay hidden.</p>}
    {r.plate && <p><b>Approved plate: {r.plate}</b></p>}
    {r.pin && <div className="ride-pin" data-screen="RIDE-003"><h3>Check the plate first</h3><strong>{r.pin}</strong><p>Tell the driver this PIN in person. Never send it in chat or notifications. Expires {rideWhen(r.pin_expires_at)}.</p></div>}
    {driver && r.state === 'accepted' && r.plate && <form onSubmit={e => { e.preventDefault(); action('start', { pin }); setPin(''); }}><RideField label="Customer pickup PIN"><input required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} value={pin} onChange={e => setPin(e.target.value)} /></RideField><button className="ride-primary">Verify PIN & start trip</button></form>}
    {r.state === 'in_trip' && <><p>Trip underway. Status only — no live tracking.</p>{driver && <button className="ride-primary" onClick={() => action('complete')}>Complete trip</button>}</>}
    {r.reason && <p>{r.reason}</p>}
    {['requested', 'accepted'].includes(r.state) && <div data-screen="RIDE-010"><button onClick={() => setCancel(!cancel)}>Cancel ride</button>{cancel && <div className="ride-alert"><h3>Confirm cancellation</h3><p>Fee: ₹0. Both sides will be notified. This cannot be undone.</p><RideField label="Cancellation reason"><textarea value={reason} onChange={e => setReason(e.target.value)} /></RideField><button disabled={!reason.trim()} onClick={() => action('cancel', { reason, confirm: true })}>Confirm free cancellation</button><button onClick={() => setCancel(false)}>Keep ride</button></div>}</div>}
    {driver && r.state === 'accepted' && <div data-screen="RIDE-015"><RideField label="Late / no-show explanation"><input value={reason} onChange={e => setReason(e.target.value)} /></RideField><button disabled={!reason.trim()} onClick={() => action('late', { reason })}>Report driver late</button><button disabled={!reason.trim()} onClick={() => action('no-show', { reason })}>Request no-show review</button><p>No-show review opens 15 minutes after pickup. No automatic fee.</p></div>}
  </RidePanel><div>{r.state === 'completed' && <RidePanel id="RIDE-004" title="Receipt & payment"><div className="ride-fare"><span>Preview total</span><strong>{rupees(r.quote.fare.total)}</strong></div><p>{r.payment_state} · payout {r.payout_state}</p>{r.payment_state !== 'paid' && r.payment_state !== 'refunded' && (driver && r.quote.payment === 'cash' ? <button className="ride-primary" onClick={() => action('cash')}>Mark test cash received</button> : !driver && r.quote.payment === 'hpay_test' ? <><button className="ride-primary" onClick={() => action('pay', { test_outcome: 'success' })}>Pay / retry HPay Test</button><button data-screen="RIDE-011" onClick={() => action('pay', { test_outcome: 'fail' })}>Test payment failure</button></> : <p>Waiting for payment confirmation.</p>)}{r.ledger.map(l => <p key={l.reference}><b>{l.kind}: {rupees(l.amount)}</b><br />{l.payment} · {l.reference}</p>)}<p>Cash stays cash. HPay Test is a local simulation, with no wallet debit or real charge.</p><div data-screen="RIDE-016"><RideField label="Rate the other participant"><select value={stars} onChange={e => setStars(Number(e.target.value))}>{[5, 4, 3, 2, 1].map(n => <option key={n} value={n}>{n} stars</option>)}</select></RideField><button onClick={() => action('rating', { stars })}>Save rating</button></div></RidePanel>}
    <RidePanel id="RIDE-012" title="Support for this ride"><RideField label="Case type"><select value={kind} onChange={e => setKind(e.target.value)}>{['support', 'lost_item', 'incident', 'refund', 'fee_review', 'appeal', 'cash_dispute'].map(k => <option key={k} value={k}>{k.replaceAll('_', ' ')}</option>)}</select></RideField><RideField label="What happened? Do not include PINs or phone numbers."><textarea value={reason} onChange={e => setReason(e.target.value)} maxLength={300} /></RideField><button disabled={!reason.trim()} onClick={() => action('support', { kind, reason })}>Send to local staff queue</button></RidePanel></div></div>;
}

function OfferClock({ until }) { const [now,setNow]=useState(Date.now()); useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);const seconds=Math.max(0,Math.ceil((Date.parse(until)-now)/1000));return <p role="timer">{seconds ? `Offer expires in ${seconds}s` : "Offer expired — refreshing confirmed status…"}</p>; }
